import type { CodeLine } from "@/lib/algorithms/types";

export const BFS_CODE: Record<"python" | "javascript" | "cpp", CodeLine[]> = {
  python: [
    { id: "fn-def", text: "def bfs(graph, source):" },
    { id: "init-visited", text: "    visited = {source}" },
    { id: "init-queue", text: "    queue = [source]" },
    { id: "init-parent", text: "    parent = {source: None}" },
    { id: "loop", text: "    while queue:" },
    { id: "dequeue", text: "        u = queue.pop(0)" },
    { id: "neighbors", text: "        for v in graph[u]:" },
    { id: "discover", text: "            if v not in visited:" },
    { id: "mark-visited", text: "                visited.add(v)" },
    { id: "set-parent", text: "                parent[v] = u" },
    { id: "enqueue", text: "                queue.append(v)" },
    { id: "path", text: "    # shortest path: walk parent to source" },
    { id: "done", text: "    # done: parent is the BFS tree" },
  ],
  javascript: [
    { id: "fn-def", text: "function bfs(graph, source) {" },
    { id: "init-visited", text: "  const visited = new Set([source]);" },
    { id: "init-queue", text: "  const queue = [source];" },
    { id: "init-parent", text: "  const parent = { [source]: null };" },
    { id: "loop", text: "  while (queue.length > 0) {" },
    { id: "dequeue", text: "    const u = queue.shift();" },
    { id: "neighbors", text: "    for (const v of graph[u]) {" },
    { id: "discover", text: "      if (!visited.has(v)) {" },
    { id: "mark-visited", text: "        visited.add(v);" },
    { id: "set-parent", text: "        parent[v] = u;" },
    { id: "enqueue", text: "        queue.push(v);" },
    { id: "path", text: "  // shortest path: walk parent to source" },
    { id: "done", text: "  // done: parent is the BFS tree" },
  ],
  cpp: [
    { id: "fn-def", text: "void bfs(vector<vector<int>>& graph, int source) {" },
    { id: "init-visited", text: "  unordered_set<int> visited = {source};" },
    { id: "init-queue", text: "  queue<int> q; q.push(source);" },
    { id: "init-parent", text: "  unordered_map<int, int> parent; parent[source] = -1;" },
    { id: "loop", text: "  while (!q.empty()) {" },
    { id: "dequeue", text: "    int u = q.front(); q.pop();" },
    { id: "neighbors", text: "    for (int v : graph[u]) {" },
    { id: "discover", text: "      if (!visited.count(v)) {" },
    { id: "mark-visited", text: "        visited.insert(v);" },
    { id: "set-parent", text: "        parent[v] = u;" },
    { id: "enqueue", text: "        q.push(v);" },
    { id: "path", text: "  // shortest path: walk parent to source" },
    { id: "done", text: "  // done: parent is the BFS tree" },
  ],
};
