import type { CodeLine } from "@/lib/algorithms/types";

export const TOPO_SORT_CODE: Record<"python" | "javascript" | "cpp", CodeLine[]> = {
  python: [
    { id: "fn-def", text: "def topo_sort(graph):" },
    { id: "init-indegree", text: "    indegree = {u: 0 for u in graph}" },
    { id: "count-u", text: "    for u in graph:" },
    { id: "count-v", text: "        for v in graph[u]: indegree[v] += 1" },
    { id: "init-queue", text: "    queue = [u for u in graph if indegree[u] == 0]" },
    { id: "init-order", text: "    order = []" },
    { id: "loop", text: "    while queue:" },
    { id: "dequeue", text: "        u = queue.pop(0)" },
    { id: "append", text: "        order.append(u)" },
    { id: "neighbors", text: "        for v in graph[u]:" },
    { id: "decrement", text: "            indegree[v] -= 1" },
    { id: "enqueue", text: "            if indegree[v] == 0: queue.append(v)" },
    { id: "cycle", text: "    # leftover nodes never reached in-degree 0 — cycle" },
    { id: "done", text: "    # done: order is a valid topological sort (DFS finishing times also work)" },
  ],
  javascript: [
    { id: "fn-def", text: "function topoSort(graph) {" },
    { id: "init-indegree", text: "  const indegree = Object.fromEntries(Object.keys(graph).map((u) => [u, 0]));" },
    { id: "count-u", text: "  for (const u of Object.keys(graph)) {" },
    { id: "count-v", text: "    for (const v of graph[u]) indegree[v] += 1;" },
    { id: "init-queue", text: "  const queue = Object.keys(graph).filter((u) => indegree[u] === 0).map(Number);" },
    { id: "init-order", text: "  const order = [];" },
    { id: "loop", text: "  while (queue.length > 0) {" },
    { id: "dequeue", text: "    const u = queue.shift();" },
    { id: "append", text: "    order.push(u);" },
    { id: "neighbors", text: "    for (const v of graph[u]) {" },
    { id: "decrement", text: "      indegree[v] -= 1;" },
    { id: "enqueue", text: "      if (indegree[v] === 0) queue.push(v);" },
    { id: "cycle", text: "  // leftover nodes never reached in-degree 0 — cycle" },
    { id: "done", text: "  // done: order is a valid topological sort (DFS finishing times also work)" },
  ],
  cpp: [
    { id: "fn-def", text: "vector<int> topoSort(vector<vector<int>>& graph) {" },
    { id: "init-indegree", text: "  vector<int> indegree(graph.size(), 0);" },
    { id: "count-u", text: "  for (int u = 0; u < (int)graph.size(); ++u) {" },
    { id: "count-v", text: "    for (int v : graph[u]) indegree[v]++;" },
    { id: "init-queue", text: "  queue<int> q; for (int u = 0; u < (int)graph.size(); ++u) if (indegree[u] == 0) q.push(u);" },
    { id: "init-order", text: "  vector<int> order;" },
    { id: "loop", text: "  while (!q.empty()) {" },
    { id: "dequeue", text: "    int u = q.front(); q.pop();" },
    { id: "append", text: "    order.push_back(u);" },
    { id: "neighbors", text: "    for (int v : graph[u]) {" },
    { id: "decrement", text: "      indegree[v]--;" },
    { id: "enqueue", text: "      if (indegree[v] == 0) q.push(v);" },
    { id: "cycle", text: "  // leftover nodes never reached in-degree 0 — cycle" },
    { id: "done", text: "  // done: order is a valid topological sort (DFS finishing times also work)" },
  ],
};
