import type { CodeLine } from "@/lib/algorithms/types";

export const DFS_CODE: Record<"python" | "javascript" | "cpp", CodeLine[]> = {
  python: [
    { id: "fn-def", text: "def dfs(graph, source):" },
    { id: "init-visited", text: "    visited = set()" },
    { id: "init-stack", text: "    stack = [source]" },
    { id: "init-parent", text: "    parent = {source: None}" },
    { id: "loop", text: "    while stack:" },
    { id: "pop", text: "        u = stack.pop()" },
    { id: "skip-visited", text: "        if u in visited:" },
    { id: "continue", text: "            continue" },
    { id: "mark-visited", text: "        visited.add(u)" },
    { id: "neighbors", text: "        for v in reversed(graph[u]):" },
    { id: "discover", text: "            if v not in visited:" },
    { id: "set-parent", text: "                parent[v] = u" },
    { id: "push", text: "                stack.append(v)" },
    { id: "path", text: "    # DFS tree path: walk parent to source" },
    { id: "done", text: "    # done: parent is the DFS tree, not shortest paths" },
    { id: "recursive-note", text: "    # recursive dfs(u) then backtrack is equivalent" },
  ],
  javascript: [
    { id: "fn-def", text: "function dfs(graph, source) {" },
    { id: "init-visited", text: "  const visited = new Set();" },
    { id: "init-stack", text: "  const stack = [source];" },
    { id: "init-parent", text: "  const parent = { [source]: null };" },
    { id: "loop", text: "  while (stack.length > 0) {" },
    { id: "pop", text: "    const u = stack.pop();" },
    { id: "skip-visited", text: "    if (visited.has(u)) {" },
    { id: "continue", text: "      continue;" },
    { id: "mark-visited", text: "    visited.add(u);" },
    { id: "neighbors", text: "    for (const v of [...graph[u]].reverse()) {" },
    { id: "discover", text: "      if (!visited.has(v)) {" },
    { id: "set-parent", text: "        parent[v] = u;" },
    { id: "push", text: "        stack.push(v);" },
    { id: "path", text: "  // DFS tree path: walk parent to source" },
    { id: "done", text: "  // done: parent is the DFS tree, not shortest paths" },
    { id: "recursive-note", text: "  // recursive dfs(u) then backtrack is equivalent" },
  ],
  cpp: [
    { id: "fn-def", text: "void dfs(vector<vector<int>>& graph, int source) {" },
    { id: "init-visited", text: "  unordered_set<int> visited;" },
    { id: "init-stack", text: "  stack<int> st; st.push(source);" },
    { id: "init-parent", text: "  unordered_map<int, int> parent; parent[source] = -1;" },
    { id: "loop", text: "  while (!st.empty()) {" },
    { id: "pop", text: "    int u = st.top(); st.pop();" },
    { id: "skip-visited", text: "    if (visited.count(u)) {" },
    { id: "continue", text: "      continue;" },
    { id: "mark-visited", text: "    visited.insert(u);" },
    { id: "neighbors", text: "    for (int i = (int)graph[u].size() - 1; i >= 0; --i) {" },
    { id: "discover", text: "      int v = graph[u][i]; if (!visited.count(v)) {" },
    { id: "set-parent", text: "        parent[v] = u;" },
    { id: "push", text: "        st.push(v);" },
    { id: "path", text: "  // DFS tree path: walk parent to source" },
    { id: "done", text: "  // done: parent is the DFS tree, not shortest paths" },
    { id: "recursive-note", text: "  // recursive dfs(u) then backtrack is equivalent" },
  ],
};
