import type { CodeLine } from "@/lib/algorithms/types";

export const DIJKSTRA_CODE: Record<"python" | "javascript" | "cpp", CodeLine[]> = {
  python: [
    { id: "fn-def", text: "def dijkstra(graph, source):" },
    { id: "init-dist", text: "    dist = {u: inf for u in graph}; dist[source] = 0" },
    { id: "init-parent", text: "    parent = {source: None}" },
    { id: "init-pq", text: "    pq = [(0, source)]  # binary heap; naive min-scan is OK" },
    { id: "init-settled", text: "    settled = set()" },
    { id: "loop", text: "    while pq:" },
    { id: "extract-min", text: "        u = heappop(pq)[1]  # extract-min" },
    { id: "skip-settled", text: "        if u in settled:" },
    { id: "continue", text: "            continue" },
    { id: "mark-settled", text: "        settled.add(u)" },
    { id: "neighbors", text: "        for v, w in graph[u]:" },
    { id: "relax", text: "            if dist[u] + w < dist[v]:  # relax" },
    { id: "update-dist", text: "                dist[v] = dist[u] + w" },
    { id: "set-parent", text: "                parent[v] = u" },
    { id: "push", text: "                heappush(pq, (dist[v], v))  # decrease-key" },
    { id: "path", text: "    # shortest path: walk parent to source" },
    { id: "done", text: "    # done: parent is the shortest-path tree" },
  ],
  javascript: [
    { id: "fn-def", text: "function dijkstra(graph, source) {" },
    { id: "init-dist", text: "  const dist = Object.fromEntries([...Object.keys(graph)].map((u) => [u, Infinity])); dist[source] = 0;" },
    { id: "init-parent", text: "  const parent = { [source]: null };" },
    { id: "init-pq", text: "  const pq = [[0, source]]; // binary heap; naive min-scan is OK" },
    { id: "init-settled", text: "  const settled = new Set();" },
    { id: "loop", text: "  while (pq.length > 0) {" },
    { id: "extract-min", text: "    pq.sort((a, b) => a[0] - b[0]); const u = pq.shift()[1]; // extract-min" },
    { id: "skip-settled", text: "    if (settled.has(u)) {" },
    { id: "continue", text: "      continue;" },
    { id: "mark-settled", text: "    settled.add(u);" },
    { id: "neighbors", text: "    for (const [v, w] of graph[u]) {" },
    { id: "relax", text: "      if (dist[u] + w < dist[v]) { // relax" },
    { id: "update-dist", text: "        dist[v] = dist[u] + w;" },
    { id: "set-parent", text: "        parent[v] = u;" },
    { id: "push", text: "        pq.push([dist[v], v]); // decrease-key" },
    { id: "path", text: "  // shortest path: walk parent to source" },
    { id: "done", text: "  // done: parent is the shortest-path tree" },
  ],
  cpp: [
    { id: "fn-def", text: "void dijkstra(vector<vector<pair<int,int>>>& graph, int source) {" },
    { id: "init-dist", text: "  vector<long long> dist(graph.size(), LLONG_MAX); dist[source] = 0;" },
    { id: "init-parent", text: "  unordered_map<int, int> parent; parent[source] = -1;" },
    { id: "init-pq", text: "  priority_queue<pair<long long,int>, vector<pair<long long,int>>, greater<>> pq; pq.push({0, source}); // heap; naive min-scan is OK" },
    { id: "init-settled", text: "  unordered_set<int> settled;" },
    { id: "loop", text: "  while (!pq.empty()) {" },
    { id: "extract-min", text: "    int u = pq.top().second; pq.pop(); // extract-min" },
    { id: "skip-settled", text: "    if (settled.count(u)) {" },
    { id: "continue", text: "      continue;" },
    { id: "mark-settled", text: "    settled.insert(u);" },
    { id: "neighbors", text: "    for (auto [v, w] : graph[u]) {" },
    { id: "relax", text: "      if (dist[u] + w < dist[v]) { // relax" },
    { id: "update-dist", text: "        dist[v] = dist[u] + w;" },
    { id: "set-parent", text: "        parent[v] = u;" },
    { id: "push", text: "        pq.push({dist[v], v}); // decrease-key" },
    { id: "path", text: "  // shortest path: walk parent to source" },
    { id: "done", text: "  // done: parent is the shortest-path tree" },
  ],
};
