import type { CodeLine } from "@/lib/algorithms/types";

export const LCS_CODE: Record<"python" | "javascript" | "cpp", CodeLine[]> = {
  python: [
    { id: "fn-def", text: "def lcs(x, y):" },
    { id: "init-table", text: "    dp = [[0]*(len(y)+1) for _ in range(len(x)+1)]" },
    { id: "loop-i", text: "    for i in range(1, len(x)+1):" },
    { id: "loop-j", text: "        for j in range(1, len(y)+1):" },
    { id: "compare", text: "            if x[i-1] == y[j-1]:" },
    { id: "match", text: "                dp[i][j] = dp[i-1][j-1] + 1  # match, take diagonal" },
    { id: "skip", text: "            else: dp[i][j] = max(dp[i-1][j], dp[i][j-1])  # skip-X / skip-Y" },
    { id: "length-done", text: "    # length is dp[m][n]" },
    { id: "reconstruct-init", text: "    i, j, out = len(x), len(y), []" },
    { id: "reconstruct-match", text: "    # match: prepend char, move diagonal" },
    { id: "reconstruct-skip", text: "    # else move to the larger neighbor" },
    { id: "reconstruct-empty", text: "    # no common subsequence" },
    { id: "done", text: "    return ''.join(reversed(out))" },
  ],
  javascript: [
    { id: "fn-def", text: "function lcs(x, y) {" },
    { id: "init-table", text: "  const dp = Array.from({ length: x.length + 1 }, () => Array(y.length + 1).fill(0));" },
    { id: "loop-i", text: "  for (let i = 1; i <= x.length; i++) {" },
    { id: "loop-j", text: "    for (let j = 1; j <= y.length; j++) {" },
    { id: "compare", text: "      if (x[i - 1] === y[j - 1]) {" },
    { id: "match", text: "        dp[i][j] = dp[i - 1][j - 1] + 1; // match, take diagonal" },
    { id: "skip", text: "      } else dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]); // skip-X / skip-Y" },
    { id: "length-done", text: "  // length is dp[m][n]" },
    { id: "reconstruct-init", text: "  let i = x.length, j = y.length, out = [];" },
    { id: "reconstruct-match", text: "  // match: prepend char, move diagonal" },
    { id: "reconstruct-skip", text: "  // else move to the larger neighbor" },
    { id: "reconstruct-empty", text: "  // no common subsequence" },
    { id: "done", text: "  return out.reverse().join('');" },
  ],
  cpp: [
    { id: "fn-def", text: "string lcs(const string& x, const string& y) {" },
    { id: "init-table", text: "  vector<vector<int>> dp(x.size()+1, vector<int>(y.size()+1, 0));" },
    { id: "loop-i", text: "  for (int i = 1; i <= (int)x.size(); ++i) {" },
    { id: "loop-j", text: "    for (int j = 1; j <= (int)y.size(); ++j) {" },
    { id: "compare", text: "      if (x[i-1] == y[j-1]) {" },
    { id: "match", text: "        dp[i][j] = dp[i-1][j-1] + 1; // match, take diagonal" },
    { id: "skip", text: "      } else dp[i][j] = max(dp[i-1][j], dp[i][j-1]); // skip-X / skip-Y" },
    { id: "length-done", text: "  // length is dp[m][n]" },
    { id: "reconstruct-init", text: "  int i = (int)x.size(), j = (int)y.size(); string out;" },
    { id: "reconstruct-match", text: "  // match: prepend char, move diagonal" },
    { id: "reconstruct-skip", text: "  // else move to the larger neighbor" },
    { id: "reconstruct-empty", text: "  // no common subsequence" },
    { id: "done", text: "  reverse(out.begin(), out.end()); return out;" },
  ],
};
